screen.columns = 1
screen = WAVE_AMPLITUDE FOG SHADOW_MAP SHADOW_RANGE SHADOW_RADIUS LIGHTING_AMBIENT LIGHTING_DIFFUSE LIGHTING_SPECULAR LIGHTING_SHININESS
sliders = WAVE_AMPLITUDE SHADOW_MAP SHADOW_RANGE SHADOW_RADIUS LIGHTING_AMBIENT LIGHTING_DIFFUSE LIGHTING_SPECULAR LIGHTING_SHININESS